@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMsInR5cGUiOiJBRE1JTiIsImVtYWlsIjoibGVvbkB0ZXN0LmNvbSIsIm5hbWUiOiJMRU9OQVJETyBOUVVBUkVTTUEiLCJpYXQiOjE3NzcwNjk0MjcsImV4cCI6MTc3NzE1NTgyN30.dcncZph4NRMjRvt2oVEXSrOX8sA6ojt8yxQ7ErkStGs

### criando categoria
POST http://localhost:3000/categorie HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
    "name":"fisioterapia",          
    "description":"fisioterapia e reabilitação"       
}

### criando categoria
POST https://uc13-projeto-2xiu.onrender.com/categorie HTTP/1.1
content-type: application/json

{
    "name":"ti",          
    "description":"cursos de tecnologia da informação"       
}


### Listar todas as categorias ? -> query
# chave=valor
GET https://uc13-projeto-2xiu.onrender.com/categorie HTTP/1.1
content-type: application/json

### Filtrar categorias por descrição (Exemplo de Query)
GET http://localhost:3000/categorie?description=design HTTP/1.1
content-type: application/json

### Mostrar uma única categoria por ID (Rota Aberta)
GET http://localhost:3000/categorie/1 HTTP/1.1
content-type: application/json

### Editar Categoria (Requer Token de ADM)
PUT https://uc13-projeto-2xiu.onrender.com/categorie/9 HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
    "name": "Estética Avançada",          
    "description": "Curso presencial e a distância na área de estética, focando em conceitos, estilos, técnicas e tendências da área."       
}

### Deletar Categoria (Requer Token de ADM)
DELETE http://localhost:3000/categorie/2 HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}