### criando categoria
POST https://uc13-projeto-2xiu.onrender.com/categorie HTTP/1.1
content-type: application/json

{
    "name":"ti",          
    "description":"de ficas"       
}

### criando categoria
POST https://uc13-projeto-2xiu.onrender.com/categorie HTTP/1.1
content-type: application/json

{
    "name":"ti",          
    "description":"cursos de tecnologia da informação"       
}

### Listar todas as categorias ? -> query
### chave=valor
GET https://uc13-projeto-2xiu.onrender.com/categorie HTTP/1.1
content-type: application/json

###
GET  https://uc13-projeto-2xiu.onrender.com/categorie?description HTTP/1.1
content-type: application/json

### Mostrar uma única categoria /2 => /:id , id se chama params

GET https://uc13-projeto-2xiu.onrender.com/categorie/9 HTTP/1.1
content-type: application/json

### Editar 

PUT https://uc13-projeto-2xiu.onrender.com/categorie/9 HTTP/1.1
content-type: application/json

{
    "name":"Estética",          
    "description":"Curso presencial e a distância na área de estética, focando em conceitos, estilos, técnicas e tendências da área."       
}

### Delete

DELETE https://uc13-projeto-2xiu.onrender.com/categorie/1 HTTP/1.1
content-type: application/json
 