#### criando companhia 
POST https://uc13-projeto-2xiu.onrender.com/companie HTTP/1.1
content-type: application/json

{
    "name": "SERVICO NACIONAL DE APRENDIZAGEM COMERCIAL SENAC",          
    "cnpj": "03.709.814/0051-57",           
    "foundation": "1970-05-12T03:00:00.000Z",       
    "places": "RR EPISCOPAL 700",      
    "fundaments": "Estudos",    
    "methods": "Superior"         
}

#### criando companhia 
POST https://uc13-projeto-2xiu.onrender.com/companie HTTP/1.1
content-type: application/json

{
    "name": "ETEC CARLOS BOTELHO",          
    "cnpj": "62.823.257/0091-57",           
    "foundation": "2000-10-25T00:00:00.000Z",       
    "places": "RUA CASA DO PEDRAO",      
    "fundaments": "CASA",    
    "methods": "ENSINO MEDIO"         
}

### Listar todos as companhias ? -> query
### chave-valor

GET https://uc13-projeto-2xiu.onrender.com/companie?name=SERVICO NACIONAL DE APRENDIZAGEM COMERCIAL SENAC HTTP/1.1
content-type: application/json

### Mostrar uma unica companhia /2 => /:id , id se chama params

GET https://uc13-projeto-2xiu.onrender.com/companie?cnpj/ HTTP/1.1
content-type: application/json  

###
GET https://uc13-projeto-2xiu.onrender.com/companie/1 HTTP/1.1
content-type: application/json  

### editar
PUT https://uc13-projeto-2xiu.onrender.com/companie/1 HTTP/1.1
content-type: application/json

{
    "name": "SERVICO NACIONAL DE APRENDIZAGEM INDUSTRIAL SENAI",          
    "cnpj": "33.564.543/0067-17",           
    "foundation": "55673-05-12T03:00:00.000Z",       
    "places": "RUA ANTONIO MICUCCI 350",      
    "fundaments": "ESTUDOS",    
    "methods": "ENSINO MEDIO"         
}


### deletando um usuario

DELETE https://uc13-projeto-2xiu.onrender.com/companie/2 HTTP/1.1
content-type: application/json


