#### criando companhia 
POST https://uc13-projeto-2xiu.onrender.com/companie HTTP/1.1
content-type: application/json

{
    "name": "SERVICO NACIONAL DE APRENDIZAGEM COMERCIAL SENAC",          
    "cnpj": "03.709.814/0051-57",           
    "foundation": "1970-05-12T03:00:00.000Z",       
    "places": "RR EPISCOPAL 700",      
    "fundaments": "Estudos",    
    "methods": "Superior"         
}

#### criando companhia 
POST http://localhost:3000/companie HTTP/1.1
content-type: application/json

{
    "name": "SERVICO NACIONAL DE APRENDIZAGEM COMERCIAL SENAC",          
    "cnpj": "03.709.814/0051-57",           
    "foundation": "1970-05-12T03:00:00.000Z",       
    "places": "RR EPISCOPAL 700",      
    "fundaments": "Estudos",    
    "methods": "Superior"         
}

### Listar todos as companhias ? -> query
### chave-valor

GET http://localhost:3000/companie?name=SERVICO NACIONAL DE APRENDIZAGEM COMERCIAL SENAC HTTP/1.1
content-type: application/json

### Mostrar uma unica companhia /2 => /:id , id se chama params

GET http://localhost:3000/companie?cnpj/ HTTP/1.1
content-type: application/json  

###
GET http://localhost:3000/companie/1 HTTP/1.1
content-type: application/json  

### editar
PUT http://localhost:3000/companie/1 HTTP/1.1
content-type: application/json

{
    "name": "CERVICO NACIONAL DE APRENDIZAGEM COMERCIAL SENAC",          
    "cnpj": "02.709.814/0051-57",           
    "foundation": "2970-05-12T03:00:00.000Z",       
    "places": "RP EPISCOPAL 700",      
    "fundaments": "Istudos",    
    "methods": "Cuperior"         
}


### deletando um usuario

DELETE http://localhost:3000/companie/2 HTTP/1.1
content-type: application/json

