### criando um curso
POST http://localhost:3000/course HTTP/1.1
content-type: application/json

{
    "name":"Tecnico em Informatica",
    "description" : "O curso Técnico em Informática prepara profissionais para atuar em diversas áreas da tecnologia da informação",
    "workload": 2000,
    "ranking": 1, 
    "fieldOfStudy":"Tecnologia",
    "companyId":1 
}

### Listar todos os cursos ? -> query
### chave=valor
GET http://localhost:3000/course?name=Inf HTTP/1.1
content-type: application/json

###

GET http://localhost:3000/course?workload_max=2000  HTTP/1.1
content-type: application/json

###
GET http://localhost:3000/course?workload_min=100  HTTP/1.1
content-type: application/json



###
GET http://localhost:3000/course?ranking HTTP/1.1
content-type: application/json

###
GET http://localhost:3000/course?ranking_max=5 HTTP/1.1
content-type: application/json

###
GET http://localhost:3000/course?ranking_min=1 HTTP/1.1
content-type: application/json





### Mostrar um unico usuário / 2 =>

GET http://localhost:3000/course/2 HTTP/1.1
content-type: application/json

