### Login de usuário
# @name login
POST http://localhost:3000/user/login HTTP/1.1
Content-Type: application/json

{
  "email": "leon@test.com",
  "password": "senhasegura"
}


### criando um curso
POST https://uc13-projeto-2xiu.onrender.com/course HTTP/1.1
Authorization: Bearer {{login.response.body.token}}
content-type: application/json

{
    "name":"Tecnico em Loistica",
    "description" : "O curso Técnico ",
    "workload": 2000,
    "ranking": 6, 
    "urlImg":"https://leschefsacademia.com.br/upload/09092020124641.png",
    "fieldOfStudy":"Tecnologia"
    
}

### criando um curso Teste Diretor
POST http://localhost:3000/course HTTP/1.1
Authorization: Bearer {{login.response.body.token}}
content-type: application/json

{
    "name":"Tecnico em ADM",
    "description" : "O curso Técnico em ADM ",
    "workload": 2000,
    "ranking": 6, 
    "urlImg":"https://leschefsacademia.com.br/upload/09092020124641.png",
    "fieldOfStudy":"Administração"
    
    
}




### criando um curso Teste ADM
POST http://localhost:3000/course HTTP/1.1
Authorization: Bearer {{login.response.body.token}}
content-type: application/json

{
    "name":"Tecnico em ADM",
    "description" : "O curso Técnico em ADM ",
    "workload": 2000,
    "ranking": 6, 
    "urlImg":"https://leschefsacademia.com.br/upload/09092020124641.png",
    "fieldOfStudy":"Administração",
    "companyId":1
    
}

### Listar todos os cursos ? -> query
# chave=valor

# Names
GET https://uc13-projeto-2xiu.onrender.com/course?name=inf HTTP/1.1
content-type: application/json

# Description
GET https://uc13-projeto-2xiu.onrender.com/course?description=Inf HTTP/1.1


# Workload
GET https://uc13-projeto-2xiu.onrender.com/course?workload_max=2000  HTTP/1.1
content-type: application/json

###
GET https://uc13-projeto-2xiu.onrender.com/course?workload_min=100  HTTP/1.1
content-type: application/json


### listar todos o curso
GET http://localhost:3000/course HTTP/1.1
content-type: application/json



### Rankings
GET https://uc13-projeto-2xiu.onrender.com/course?ranking HTTP/1.1
content-type: application/json

#
GET https://uc13-projeto-2xiu.onrender.com/course?ranking_max=5 HTTP/1.1
content-type: application/json

#
GET https://uc13-projeto-2xiu.onrender.com/course?ranking_min=1 HTTP/1.1
content-type: application/json

### Mostrar um unico usuário / 2 =>

GET https://uc13-projeto-2xiu.onrender.com/course/5 HTTP/1.1
content-type: application/json

### Realiza uma mudança;

PUT https://uc13-projeto-2xiu.onrender.com/course/3 HTTP/1.1
content-type : application/json

{
  "name":"Tecnico em Enfermagem",
  "description" : "O curso Técnico em Informática prepara profissionais para atuar em diversas áreas da tecnologia da informação"
}
### Editando o curso;

PUT http://localhost:3000/course/1 HTTP/1.1
content-type : application/json

{
  "name":"Tecnico em Administração",
  "description" : "O curso Técnico em Administração prepara profissionais para atuar em diversas áreas da administração"
}

####
PUT https://uc13-projeto-2xiu.onrender.com/course/1 HTTP/1.1
content-type: application/json


{
  "name":"Tecnico em Batatinha"
 
}

### DELETE
DELETE https://uc13-projeto-2xiu.onrender.com/course/5 HTTP/1.1
content-type: application/json


