### criando um curso
POST https://uc13-projeto-2xiu.onrender.com/course HTTP/1.1
content-type: application/json

{
    "name":"Tecnico em Logistica",
    "description" : "O curso Técnico ",
    "workload": 2000,
    "ranking": 6, 
    "urlImg":"https://leschefsacademia.com.br/upload/09092020124641.png",
    "fieldOfStudy":"Tecnologia",
    "companyId":2
}

### Listar todos os cursos ? -> query
### chave=valor


### Names
GET http://localhost:3000/course?name=inf HTTP/1.1
content-type: application/json

### Description
GET http://localhost:3000/course?description=Inf HTTP/1.1


### Workload

GET http://localhost:3000/course?workload_max=2000  HTTP/1.1
content-type: application/json

###
GET http://localhost:3000/course?workload_min=100  HTTP/1.1
content-type: application/json



### Rankings
GET http://localhost:3000/course?ranking HTTP/1.1
content-type: application/json

###
GET http://localhost:3000/course?ranking_max=5 HTTP/1.1
content-type: application/json

###
GET http://localhost:3000/course?ranking_min=1 HTTP/1.1
content-type: application/json

### Mostrar um unico usuário / 2 =>

GET http://localhost:3000/course/5 HTTP/1.1
content-type: application/json

### Realiza uma mudança;

PUT http://localhost:3000/course/99 HTTP/1.1
content-type : application/json

{
  "name":"Tecnico em Enfermagem",
  "description" : "O curso Técnico em Informática prepara profissionais para atuar em diversas áreas da tecnologia da informação"
}

###
PUT http://localhost:3000/course/1 HTTP/1.1
content-type: application/json


{
  "name":"Tecnico em Batatinha"
 
}

### DELETE
DELETE http://localhost:3000/course/5 HTTP/1.1
content-type: application/json


