### criando um usuario completo
POST http://localhost:3000/user/ HTTP/1.1
Content-Type: application/json

{
  "name": "Vanessa",
  "cpf": "12345678900",
  "email": "vanessa@email.com",
  "type": "ADMIN",
  "status": "ATIVO",
  "birthDate": "1995-05-10T00:00:00.000Z"
}

### criando um usuario completo
POST http://localhost:3000/user/ HTTP/1.1
Content-Type: application/json

{
  "name": "Kevin",
  "cpf": "12345678911",
  "email": "kevin@email.com",
  "type": "TEACHER",
  "status": "INATIVO",
  "birthDate": "2005-05-10T00:00:00.000Z"
}


### Listar todos os usuários
GET http://localhost:3000/user/ HTTP/1.1
content-type:aplication.json

### Filtrar pelo atributo nome
GET http://localhost:3000/user?name=Vanessa HTTP/1.1
content-type:aplication.json

### Filtrar pelo status
GET http://localhost:3000/user?status=ATIVO HTTP/1.1
content-type:aplication.json

### Filtrar pelo tipo "TEACHER"
GET http://localhost:3000/user?type=TEACHER HTTP/1.1  
content-type:aplication.json

### Filtrar pelo tipo "ADMIN"
GET http://localhost:3000/user?type=ADMIN HTTP/1.1
content-type:aplication.json

### Mostrar um único usuário
GET http://localhost:3000/user/2 HTTP/1.1 
content-type:aplication.json

### Listar usuários nascidos entre 1990 e 2000
GET http://localhost:3000/user?birth_min=1990-01-01&birth_max=2000-12-31 HTTP/1.1 //coment
content-type: application/json

### Mostrar o usuário que eu quero editar
PUT http://localhost:3000/user/2 HTTP/1.1
Content-Type: application/json

{
  "name": "Lucas",
  "email": "lucas@email.com",
  "birthDate": "2006-05-10T00:00:00.000Z"
}

### Deletar o usuário
DELETE http://localhost:3000/user/1 HTTP/1.1
Content-Type: application/json

### Listar todos os usuários
GET http://localhost:3000/user/ HTTP/1.1
content-type:aplication.json


